Finish documenting outer classes
Galaxia5987/2020Vision pull request #4
Opened 2019-10-22 13:53 UTC by msmow

Document all the various handlers that are used in main, including utils.
Add usage of the help function when launching each file, showcasing all methods and attributes of every class.

2019-10-27 15:45 UTC, pklito requested changes

2019-10-27 15:45 UTC, pauloalbert commented on realsense.py
> +        :param exposure: Exposure to se the camera to.
```suggestion
        :param exposure: Exposure to set the camera to.
```

2019-11-01 11:04 UTC, orel-david reviewed
The documentation is clear and except this one if statement everything is pretty clear

2019-11-01 11:04 UTC, orel-david commented on main.py
> +    # Add help in main argument
What does help mean ?

2019-11-01 11:04 UTC, orel-david commented on main.py
> +    main.loop()
I think this if statement needs some documentation

2019-12-26 12:27 UTC, merged